spring:
# Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/speraignacio/Bootcamp-ConfigServer
          default-label: main
          search-paths:
          - '*service'
